[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"